### ISSUE TITLE
The code does not match the documentation or the firmware in the module we buy

### ISSUE THREAD

**Issue by KennethLavrsen** [limengdu/Seeed-Studio-MR60BHA1-Sensor#1]
I have tried to use this code for a full day.

I noticed that

Heart rate is always a low number around 15 or so.

Breating data are never recorded

When you add some debugging to the software and write out all telegrams from the module it does not match the code. 

And more importantly the module sends data that does not match the user manual.

So user manual, this code on github, and the actual modules are 3 different implementations.

I have not been able to get any useful data out of the module. Because of the mess with documentation and this code - these modules are worthless. You cannot use them for anything.

**Comment by limengdu** [comment]
Hello, this code is decoded according to the latest data format provided by R&D. Maybe our documentation has not been updated yet, but the code has been updated by one version, now please refer to the code content, thank you.

**Comment by KennethLavrsen** [comment]
Hello. Thanks. I will check out the new code this weekend and report back.

**Comment by emmadickson** [comment]
@KennethLavrsen Was this resolved for you? I just tried to use this board today and also found that the code didn't seem to make sense compared to the data stream that it was receiving.

**Comment by limengdu** [comment]
Sorry for the long wait, the program has been updated to the latest version, and the Wiki will be updated soon, so stay tuned.
