### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by andriisemenov** [limengdu/Seeed-Studio-MR60BHA1-Sensor#10]
Please update the documentation and the files.
Particularly, this step: Universal method - use J-link to burn firmware

I get error when trying to add the Artery MCUs to J-flash.
![image](https://github.com/limengdu/Seeed-Studio-MR60BHA1-Sensor/assets/17324432/63e7eccf-6caf-4edd-b6ac-68d612afd9e7)
 
 I found a way to flash it the solution is the following:
 1. Download this file 
 
![image](https://github.com/limengdu/Seeed-Studio-MR60BHA1-Sensor/assets/17324432/a365397d-03b0-4990-a296-c9f5cbc9725f)

 from https://www.arterychip.com/en/product/AT32F403A.jsp
 
 2. Unzip the file and open
 
 3. Copy JLinkDevices.xml from C:\Program Files\SEGGER\JLink_V794 to C:\Users\[User]\AppData\Roaming\SEGGER
 
 This fixes the problem and we can flash with JFlash or JFlash Lite software.

**Comment by limengdu** [comment]
Thanks for the information, we have updated the Wiki.
