### ISSUE TITLE
MR60BHA1 not wok correctly, does this mean the radar is broken? Or does it mean I need to use J-Link to make it work?

### ISSUE THREAD

**Issue by Yuyu378** [limengdu/Seeed-Studio-MR60BHA1-Sensor#11]
![image](https://github.com/user-attachments/assets/c595342b-d991-4d10-aa19-6999239e6209)
As you can see, the "Breathing Curve" and "Heart Rate Curve" are not showing. My position on the radar chart is also incorrect.

Neither updating the radar firmware with [PackageMake](https://files.seeedstudio.com/wiki/60GHzradar/new_res/PackageMake-v1.1.1.zip) via UART
![image](https://github.com/user-attachments/assets/aaac81b4-dc51-4b4b-8cd3-02d4d7e381eb)

nor printing the firmware version of the radar sensor with [COMTool](https://github.com/Neutree/COMTool/releases/download/v3.4.1/comtool_windows_v3.4.1.7z) worked. 
![image](https://github.com/user-attachments/assets/334df893-1b75-45cf-b96c-586222ac5fc5)

Does this mean the radar is broken? Or means that I need to use J-Link to make it work?
If I need to use J-Link to update the radar, which version of J-Link should I purchase? 

https://www.segger.com/products/debug-probes/j-link/#comparison
J-Link Edu mini, Base, Plus, Ultra+, Pro, or Pro PoE?

Is there any way to fix this? J-Link is too expensive.

**Comment by limengdu** [comment]
The radar is reporting data and it doesn't feel like there is a problem with the firmware.The MR60BHA1 is currently trying to get respiration and heart rate data updated with the following requirements:
1. radar is about 1.5m from the heart
2. the radar has judged the body into a sleep state
3. the body can not have movement
It is worth noting that for the radar to determine that the body has gone to sleep, then you may need to remain still for at least 20 minutes.

**Comment by Yuyu378** [comment]
Do you have a clue as to what is causing the Breath Curve and Heart Rate Curve not to show up, and the Radar Graph to show up in the wrong place?

Since I can't use the UART to update the firmware or get the firmware version from the COMTool, that's why I'm asking if it's a firmware issue.

**Comment by limengdu** [comment]
Respiration and heart rate are line graphs that appear only when there is continuous data to report.

**Comment by Yuyu378** [comment]
Alright, let's put aside for a moment the fact that the graphs of respiration and heart rate are not showing up.

I have another 2 questions here:
1. What's up with the UART failing to update the firmware and the COMTool not responding to the “Firmware version query” command sent?
2. Why the position on radar chart not changed when I walk around radar sensor? It always point at the right edge.

**Comment by limengdu** [comment]
There is no 3d point cloud mapping feature with this radar and the distance data is for reference only.

**Comment by Yuyu378** [comment]
Allow me to further state my questions.

"The position on radar chart not changed" means it would always be here.
![image](https://github.com/user-attachments/assets/f1603e4a-ff36-4d2e-bf54-1af374db57c1)

It doesn't look like it will show the situation when I'm far away from the radar sensor.
![image](https://github.com/user-attachments/assets/89efd5ee-6a23-4b12-99cd-58c9a4f7ed5d)

Or the situation when I at the left side of radar sensor.
![image](https://github.com/user-attachments/assets/16b051e0-1746-460f-b0f8-ee864175bf7b)

It would **ALWAYS** be right side.
I **KNOW** this radar has no 3d point cloud to show the actually posture I post.

-----

Another question

Failed to update firmware via UART.

Seeed Studio Wikipedia states that there are minimum firmware requirements for updating this radar sensor using UART.
![image](https://github.com/user-attachments/assets/573b58e7-b392-45a3-ae75-25dfe17597c7)

So I went and tried to get the firmware version of the radar and apparently, it did not respond.
![image](https://github.com/user-attachments/assets/1110d046-60ed-40cf-a23b-8916d70970d6)

This is the outer packaging of the radar sensor I bought.
![image](https://github.com/user-attachments/assets/7b63e138-d2d0-416b-956e-6e38e465ac90)

**Comment by limengdu** [comment]
The radar does not have any function to indicate position, so this legend on the software does not have any real meaning, including this point.
---
<img width="680" alt="image" src="https://github.com/user-attachments/assets/1c2f7437-049f-4605-a992-e5826cbb4421">
Numbers are in hexadecimal, please send them in hexadecimal.

**Comment by Yuyu378** [comment]
I **DO** send in hexadecimal.
![image](https://github.com/user-attachments/assets/3fdad5bb-5b65-4b28-98f2-4974fe8fd0a3)

If I want to know what the current firmware is, I need to receive it in ASCII, otherwise I get a string of hex codes that I can't understand.

**Comment by limengdu** [comment]
Is this the only command that didn't return? Or does it not respond no matter what you send it?

**Comment by limengdu** [comment]
Is this the only command that didn't return? Or does it not respond no matter what you send it

**Comment by Yuyu378** [comment]
Could you provide some possible valid hexadecimal code for me to test?

**Comment by limengdu** [comment]
https://files.seeedstudio.com/wiki/60GHzradar/new_res/MR60BHA1_userManual_V2.3.pdf

**Comment by Yuyu378** [comment]
I had test 
`53 59 02 A1 00 01 0F 5F 54 43` for Product model query
`53 59 02 A2 00 01 0F 60 54 43` for Product id query
`53 59 02 A3 00 01 0F 61 54 43` for Hardware model query

The Firmware version query is `53 59 02 A4 00 01 0F 62 54 43`.

It seems not respond no matter what I send.
Just keep receive report data.
![image](https://github.com/user-attachments/assets/f46bfecf-0244-4ba0-8b39-f99e24d8de80)

**Comment by limengdu** [comment]
Then I suspect the data didn't go out.

**Comment by Yuyu378** [comment]
How do I fix this issue? Does this mean that my MR60BHA1 has a bad Rx? I'm sure my USB2TTL converter is not bad, I tested it with another sensor.

**Comment by limengdu** [comment]
Do you have any other software, try changing the software, or maybe you connect the RX and TX of your TTL together to check.

**Comment by Yuyu378** [comment]
![image](https://github.com/user-attachments/assets/d430145f-6620-4f6b-add3-71540d694712)
The USB2TTL converter is functioning correctly.

Use SerialTest work, too. (The last receive is send `0123456789` in hex)
![image](https://github.com/user-attachments/assets/b36ed2e1-d73f-42df-851d-1d1929b25883)

I tried changing the software to query data form radar. Yes, no response. Just keep receive report data.
![image](https://github.com/user-attachments/assets/251e0f4f-fe4a-4ae6-820e-590ab475b283)

**Comment by limengdu** [comment]
Well, your radar may be faulty, I can confirm this now, please contact our technical support team (techsupport@seeed.io) and ask them to replace your radar product with a newer model - MR60BHA2. Please attach our communication here on the contact them email! link on the email to them. We apologize for any inconvenience caused. Our new radar has greatly optimized algorithms and we hope it will provide you with a new experience.

**Comment by Yuyu378** [comment]
All right, thank you for your time.
