### ISSUE TITLE
firmware version

### ISSUE THREAD

**Issue by alberk8** [limengdu/Seeed-Studio-MR60BHA1-Sensor#2]
I have a few questions?

1) Is there any new firmware? if so How to get it and flash.
2) I am about confused with the documentation provided by Seeed Studio.   From what I see some of the data frame are write?  is there an example of those.  

Thank you.

**Comment by limengdu** [comment]
Sorry for the long wait, the program has been updated to the latest version, and the Wiki will be updated soon, so stay tuned.
The update method for the new firmware has been updated to the Wiki.
