### ISSUE TITLE
Alternate version

### ISSUE THREAD

**Issue by AronRubin** [limengdu/Seeed-Studio-MR60BHA1-Sensor#3]
I made an alternate version of this library that suits my needs a little better. It follows the typical Arduino form of passing the serial port and exposing information as collected. I did my best to fuse a number of sources on the protocol. My hope would be that you would consider adopting a similar form. I also hope you do not find this offensive in any way.

https://github.com/AronRubin/SeeedHeartBreathRadar

Thank you,
Aron

**Comment by wijayw** [comment]
Hi Aron, thanks for sharing this alternate version. Looks very interesting from my beginner skills in C and C++. I've been trying to run it with the necessary modifications to remove the display parts of the code, with little success. What microcontroller and IDE did you use. Was it an Arduino or ESP32?

Thanks.
Wijay.

**Comment by AronRubin** [comment]
@wijayw It is running on an rp2040 based device for my debug convenience. I don't think there is anything that would prevent it from working with ESP32. When I resume the project, that is likely my target as well. We should probably discuss your issues in the repository associated with the project.

**Comment by wijayw** [comment]
Thanks Aron. Will continue the discussion on the Seeed wiki.

**Comment by limengdu** [comment]
Thank you for your interest and support of this product.
