### ISSUE TITLE
Sensor not responding

### ISSUE THREAD

**Issue by tonydee2377** [limengdu/Seeed-Studio-MR60BHA1-Sensor#4]
Hi,
My Heartbeat sensor does not respond and in serial on boot it writes this line:

 PAC 1 f4
Zone-0 Write password authentication failed
Cw0881_Check failure

what does it mean? 
is there a way to get it back?

Help Me
Tony

**Comment by limengdu** [comment]
Hello, we have not encountered similar problems. We recommend that you contact Seeed Studio's technical support for professional support on product issues. The email address is: techsupport@seeed.io.

**Comment by tonydee2377** [comment]
Everything OK,
   techsupport@seeed.io sent me the procedure to reflash the firmware. Maybe due to a little fast on/off on the power supply that I realized late some line of code in some memory area was skipped, the sensor is powered, I will try this firmware procedure, but I am confident that the sensor will recover.

Thank you
